name: Deploy templates
on: workflow_call
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: github-action-arm-rg
        template: ./azuredeploy.json
        parameters: azuredeploy.parameters.json managedInstanceName=zmoalzmi administratorLoginPass=${{ secrets.SQL_SERVER_PASSWORD }}
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear