name: Deploy templates
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: github-action-arm-rg
        template: ./azuredeploy.json
        parameters: azuredeploy.parameters.json managedInstanceName=zmoalzmi administratorLoginPass=${{ secrets.SQL_SERVER_PASSWORD }}
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"