name: Main GH Action Template
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  LOCATION: norwayeast
  RESOURCE_GROUP: demo-sqlmi-w-vm
  TEMPLATE_SPEC_VERSION: "0.1"
  TEMPLATE_SPEC_NAME: arm-private-deployment-ts
  DEPLOY_RESOURCE_GROUP: arm-private-deployment

jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.5.2
      with:
        modules: 'PSRule.Rules.Azure'
  
  build-and-deploy:
    needs: analyze_arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Verify/Create RG for Demo
      run: |
        ./scripts/rg-create.sh \
          -r ${{ env.RESOURCE_GROUP }} \
          -l ${{ env.LOCATION }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./azuredeploy.json
        parameters: azuredeploy.parameters.json managedInstanceName=zmoalzsqlmi administratorLoginPass=${{ secrets.SQL_SERVER_PASSWORD }}
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
