name: Main GH Action Template
on:
  push:
    branches:
    - main
jobs:
  PSRule:
    name: PSRule YAML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Analyze Azure template files
      uses: ./.github/workflows/PSRule
  ARMdeployment:
    name: ARMdeployment YAML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Analyze Azure template files
      uses: ./.github/workflows/ARMdeployment
