name: Main GH Action Template
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.5.2
      with:
        modules: 'PSRule.Rules.Azure'
  build-and-deploy:
    needs: analyze_arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: demo-sqlmi-w-vm
        template: ./azuredeploy.json
        parameters: azuredeploy.parameters.json managedInstanceName=zmoalzmi administratorLoginPass=${{ secrets.SQL_SERVER_PASSWORD }}
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
