name: Main GH Action Template
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch: {}
jobs:
  PSRule:
    name: PS Rule ARM Template Checker
    id: custom-action
    uses: ./.github/workflows/PSRule.yml
  ARMdeployment:
    name: ARM Template Deploy
    id: custom-action2
    uses: ./.github/workflows/ARMdeployment.yml
