name: Main GH Action Template
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch: {}
jobs:
  PSRule:
    name: PS Rule ARM Template Checker
    uses: zmo-alz/sql-mi-with-vm/.github/workflows/PSRule.yml@main
  ARMdeployment:
    name: ARM Template Deploy
    uses: zmo-alz/sql-mi-with-vm/.github/workflows/ARMdeployment.yml@main
