name: Analyze templates
on:
  workflow_call:
    inputs:
      matrix-input:
        type: string
        required: true
jobs:
  analyze_arm:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.5.2
      with:
        modules: 'PSRule.Rules.Azure'
